<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>QuerySeek</Title>
    <Authors>code64Zmafi0</Authors>
    <Description>Linked data text search engine.</Description>
    <RepositoryUrl>https://github.com/code64Zmafi0/QuerySeek</RepositoryUrl>
    <PackageTags>Text search; Index; Relations; Data;</PackageTags>
	<PackageReadmeFile>README.md</PackageReadmeFile>
	<PackageIcon>Logo.png</PackageIcon>
    <Version>1.3.0</Version>
  </PropertyGroup>

  <ItemGroup>
	<None Include="..\README.md" Pack="true" PackagePath="\" />
	<None Include="..\Logo.png" Pack="true" PackagePath="\" />
	<PackageReference Include="MessagePack" Version="3.1.7" />
  </ItemGroup>

</Project>
